"""
Django settings for alwa project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^gb+b-2a5tnm+4d6z*_jr+y@h!t#2w9%bp%_96c)s80l=%)775'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_PASSWORD = '123@dosa'
EMAIL_HOST_USER = 'biestdosa@gmail.com'
EMAIL_PORT =465
EMAIL_USE_TLS = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'about',
    'login',
    'registerAwal',
    'contact',
    'dashboard',
    'services',
    'renwal',
    'renwal.templatetags.tags',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'alwa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, '/login/templates'),
            os.path.join(BASE_DIR, '/about/templates'),
            os.path.join(BASE_DIR, '/registerAwal/templates'),
            os.path.join(BASE_DIR, '/contact/templates'),
            os.path.join(BASE_DIR, '/dashboard/templates'),
            os.path.join(BASE_DIR, '/services/templates'),
             os.path.join(BASE_DIR, '/renwal/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
            'mytags': 'renwal.templatetags.tags',

            }
        },
    },
]

WSGI_APPLICATION = 'alwa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'alwa',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'users': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'alwa',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/static/'

STATIC_FILES_URL = '/static/files/'
STATICFILES_DIRS = (
    (os.path.join(BASE_DIR, 'static')),
    )
MEDIA_ROOT = BASE_DIR
#MEDIA_ROOT = os.path.join(BASE_DIR,"media")
print "###################",MEDIA_ROOT
#MEDIA_ROOT = '/media'
CACHES = {
    
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': MEDIA_ROOT+'/myCache',#'../logs/myCache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    },
    'filecache': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': MEDIA_ROOT+'/myCache',#'../logs/myCache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    },
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s'
        },
    },
    'handlers': {
        'default': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MEDIA_ROOT+'/logs/alwa_request.log',
            'maxBytes': 1024*1024*5,
            'backupCount': 5,
            'formatter': 'simple'
        },
    'logfile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MEDIA_ROOT+'/logs/alwa_console_request.log',
            'maxBytes': 1024*1024*5,
            'backupCount': 5,
            'formatter': 'simple'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'request_handler': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MEDIA_ROOT+'/logs/alwa_request.log',
            'maxBytes': 1024*1024*5,
            'backupCount': 5,
            'formatter': 'simple'
        },
    },
 
}
APPEND_SLASH=True