# Generated by Django 2.2.6 on 2020-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('demodate', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'demo_table',
                'managed': True,
            },
        ),
    ]
